### ISSUE TITLE
Outdated project

### ISSUE THREAD

**Issue by huqedato** [koudelka/visualixir#41]
Project seems to be broken. It doesn't compile on _Elixir 1.13.2 (compiled with Erlang/OTP 22)_
After tones of warning it ends in a error:

```
== Compilation error in file lib/visualixir_web/views/layout_view.ex ==
** (RuntimeError) unexpected EEx.Engine state: {:safe, ""}. This typically means a bug or an outdated EEx.Engine or tool

    (eex 1.13.2) lib/eex/engine.ex:218: EEx.Engine.check_state!/1
    (eex 1.13.2) lib/eex/engine.ex:181: EEx.Engine.handle_text/3
    (eex 1.13.2) lib/eex/compiler.ex:52: EEx.Compiler.generate_buffer/4
    (phoenix 1.3.2) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix 1.3.2) lib/phoenix/template.ex:186: anonymous fn/3 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.3.2) expanding macro: Phoenix.Template.__before_compile__/1
    lib/visualixir_web/views/layout_view.ex:1: VisualixirWeb.LayoutView (module)
```

**Comment by koudelka** [comment]
what a bummer, fancy making a PR? :)

**Comment by huqedato** [comment]
Nope, I've been serious. This project sounded (and looked) very interesting but seems to be dead, abandoned.

**Comment by oliverswitzer** [comment]
@koudelka thanks for making such an awesome project. I tried to do an upgrade in this repo so that I could run this on my M1, but found that it was actually much easier to start from a fresh `mix phx.new` and then copy over stuff from the original project. Hope you don't mind, but I made a new repo for it 😬

For posterity / anyone who wants to get this thing running again (using Elixir 1.14.1 / Erlang 24.1):

https://github.com/oliverswitzer/vislixir
